In [ ]:
import pandas as pd

In [ ]:
train = pd.read_csv("/content/drive/MyDrive/LG_Aimers4_본선/train.csv")
test = pd.read_csv("/content/drive/MyDrive/LG_Aimers4_본선/submission.csv")

In [ ]:
# 각 피처별 고유값의 수를 계산합니다.
nunique_values = train.nunique()

# 35개 이하의 고유값을 가진 피처들을 필터링합니다.
features_with_few_unique_values = nunique_values[nunique_values <= 35].index.tolist()

# 타겟 변수 'is_converted'를 제외한 피처 리스트를 생성합니다.
features_to_encode = [feature for feature in features_with_few_unique_values if feature != 'is_converted']

# 각 피처에 대해 타겟 인코딩을 적용하고 원본 데이터프레임에 추가합니다.
for feature in features_to_encode:
    # 각 카테고리별로 'is_converted'의 평균값을 계산합니다.
    encoded_feature_name = f"{feature}_encoded"
    train[encoded_feature_name] = train.groupby(feature)['is_converted'].transform('mean')
# For each feature with 35 or fewer unique values, calculate value_counts()
value_counts_per_feature = {feature: train[feature].value_counts() for feature in features_to_encode}
value_counts_per_feature

{'bant_submit': bant_submit
 0.50    17192
 1.00    17061
 0.25    12852
 0.75    11681
 0.00      513
 Name: count, dtype: int64,
 'business_unit': business_unit
 ID          25563
 AS          24774
 IT           8664
 Solution      296
 CM              2
 Name: count, dtype: int64,
 'customer_type': customer_type
 End-Customer                    6647
 End Customer                    3996
 Specifier/ Influencer           2525
 Channel Partner                 1368
 Service Partner                  349
 Solution Eco-Partner             146
 Installer/Contractor              52
 Specifier / Influencer            43
 Corporate                         31
 HVAC Engineer                     23
 Engineer                          20
 Developer                         17
 Technician                        16
 Consultant                        15
 Other                             10
 Home Owner                        10
 Manager / Director                 8
 End-user                           8
 Software/Solution Provider         7
 Etc.                               6
 Interior Designer                  5
 Reseller                           5
 Installer                          5
 Homeowner                          5
 Architect/Consultant               5
 Others                             4
 Distributor                        4
 Dealer/Distributor                 2
 System Integrator                  2
 Administrator                      1
 Commercial end-user                1
 Technical Assistant                1
 Software / Solution Provider       1
 Name: count, dtype: int64,
 'customer_history': customer_history
 New         45543
 Existing    13756
 Name: count, dtype: int64,
 'enterprise': enterprise
 Enterprise    37783
 SMB           21516
 Name: count, dtype: int64,
 'id_strategic_ver': id_strategic_ver
 1.0    3444
 Name: count, dtype: int64,
 'it_strategic_ver': it_strategic_ver
 1.0    1121
 Name: count, dtype: int64,
 'idit_strategic_ver': idit_strategic_ver
 1.0    4565
 Name: count, dtype: int64,
 'prefer_ver_count': prefer_ver_count
 0.211618    2460
 0.145228    2028
 0.038462    1391
 0.269231    1365
 0.095436    1356
 0.288462    1278
 0.116183    1075
 0.215768     984
 0.434783     895
 0.000000     865
 0.043478     831
 0.016598     804
 0.115385     713
 0.070539     540
 0.058091     421
 0.057692     383
 0.173913     372
 0.024896     216
 0.076923     156
 0.130435     150
 0.019231      62
 0.012448      43
 1.000000      29
 Name: count, dtype: int64,
 'prefer_ver_mean': prefer_ver_mean
 0.027756    2460
 0.103511    2028
 0.003494    1365
 0.067718    1356
 0.016624    1278
 0.038886    1075
 0.046220     984
 0.445656     895
 0.000000     865
 0.208275     791
 0.008944     788
 0.391321     713
 0.049939     540
 0.068288     421
 0.449872     403
 0.044163     385
 0.072195     330
 0.025764     271
 0.106115     216
 0.005677     210
 0.067927     200
 0.110869     190
 0.032717     173
 0.019648     156
 0.130980     148
 0.003777      62
 0.290661      43
 0.052136      42
 1.000000      29
 Name: count, dtype: int64,
 'transfer_agreement': transfer_agreement
 Y    49457
 N     9312
 Name: count, dtype: int64,
 'ver_cus': ver_cus
 0    56832
 1     2467
 Name: count, dtype: int64,
 'ver_pro': ver_pro
 0    56286
 1     3013
 Name: count, dtype: int64,
 'ver_win_rate_x': ver_win_rate_x
 0.003079    4097
 0.001183    3011
 0.000717    2013
 0.000543    1929
 0.000298    1818
 0.000572    1727
 0.000060    1199
 0.000215    1035
 0.000097     650
 0.000026     519
 0.000013     306
 0.000002     113
 Name: count, dtype: int64,
 'ver_win_rate_mean_upper': ver_win_rate_mean_upper
 0.0    14595
 1.0     3822
 Name: count, dtype: int64,
 'ver_win_ratio_per_bu': ver_win_ratio_per_bu
 0.064566    2460
 0.049840    2028
 0.020121    1365
 0.048630    1356
 0.026846    1278
 0.064070    1075
 0.071345     984
 0.011583     788
 0.022634     713
 0.060924     540
 0.079412     421
 0.036913     403
 0.035484     385
 0.031579     271
 0.053571     216
 0.051471     210
 0.028777     200
 0.022727     173
 0.128571     156
 0.131148     148
 0.227273      62
 0.285714      43
 0.034483      29
 Name: count, dtype: int64,
 'business_area': business_area
 corporate / office                4097
 retail                            3011
 hotel & accommodation             2013
 special purpose                   1929
 residential (home)                1818
 education                         1727
 hospital & health care            1199
 factory                           1035
 government department              650
 public facility                    519
 transportation                     306
 power plant / renewable energy     113
 Name: count, dtype: int64}

In [ ]:
# 중복 행을 제거하고 각 중복 그룹에서 첫 번째 행만 남김
train = train.drop_duplicates()
train = train.reset_index(drop = True)
train

,bant_submit,expected_budget,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,lead_date,customer_type,customer_history,enterprise,...,transfer_agreement,ver_cus,ver_pro,ver_win_rate_x,ver_win_rate_mean_upper,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner,is_converted
0,0.75,NaN,/DKI Jakarta/Indonesia,AS,NaN,33931,2022-10-15,End-Customer,Existing,Enterprise,...,Y,0,0,0.000060,1.0,0.128571,hospital & health care,General Hospital,870,False
1,0.25,NaN,/Minneola/United States,ID,0.390244,42490,2023-05-31,NaN,New,SMB,...,N,0,0,0.000572,0.0,0.048630,education,NaN,501,True
2,0.25,NaN,4880 Stevens Creek Blvd Cloud IT/Hollywood/Un...,IT,NaN,10350,2023-04-19,Solution Eco-Partner,New,SMB,...,Y,0,0,NaN,NaN,NaN,NaN,NaN,375,True
3,1.00,"$100,000 ~ $500,000",/Wiesbaden/Germany,ID,0.017544,19750,2021-10-30,NaN,New,SMB,...,Y,0,0,0.000572,0.0,0.048630,education,NaN,359,False
4,0.50,NaN,//Singapore,ID,NaN,45802,2023-04-11,Specifier/ Influencer,New,SMB,...,Y,0,0,NaN,NaN,NaN,NaN,NaN,198,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57060,0.75,NaN,/Noida/India,ID,NaN,17289,2021-07-02,NaN,Existing,Enterprise,...,Y,0,0,NaN,NaN,NaN,NaN,NaN,174,False
57061,0.75,NaN,/Sao Bernardo do Campo/Brazil,ID,NaN,23686,2021-07-27,NaN,New,SMB,...,Y,0,0,NaN,NaN,NaN,NaN,NaN,211,False
57062,0.50,NaN,/Alexandria/Egypt,AS,0.049689,29370,2021-08-26,NaN,Existing,Enterprise,...,Y,0,0,0.000298,0.0,0.020121,residential (home),NaN,56,False
57063,0.50,NaN,/Mogi guaçu SP /Brazil,AS,NaN,22609,2022-04-25,NaN,New,Enterprise,...,Y,0,0,NaN,NaN,NaN,NaN,NaN,96,False
57064,0.50,"less_than_£7,000",//United Kingdom,IT,NaN,41443,2022-09-12,NaN,New,SMB,...,Y,0,0,NaN,NaN,NaN,NaN,NaN,384,False

In [ ]:
train[train['is_converted'] == True]

,bant_submit,expected_budget,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,lead_date,customer_type,customer_history,enterprise,...,ver_win_rate_mean_upper,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner,is_converted,lead_description_clean,lead_description_clean_simple,event_name_first_part,event_name_second_part
1,0.25,NaN,/Minneola/United States,ID,0.390244,42490,2023-05-31,NaN,New,SMB,...,0.0,0.048630,education,NaN,501,True,grant technology available,are there any grants for technology available,ID,US
2,0.25,NaN,4880 Stevens Creek Blvd Cloud IT/Hollywood/Un...,IT,NaN,10350,2023-04-19,Solution Eco-Partner,New,SMB,...,NaN,NaN,NaN,NaN,375,True,nan,nan,IT,US
23,0.75,NaN,//Hong Kong,ID,NaN,25096,2022-06-30,NaN,New,Enterprise,...,NaN,NaN,NaN,NaN,337,True,hi sell model bezel hong kong price,hi do you sell this model with no bezel in hon...,ID,HQ
60,0.75,NaN,/Navi mumbai/India,ID,NaN,32912,2023-04-08,NaN,New,Enterprise,...,NaN,NaN,NaN,NaN,145,True,cost,cost,ID,IL
65,0.25,NaN,/Peddapuram/India,AS,NaN,41227,2023-01-07,End-Customer,New,Enterprise,...,NaN,NaN,NaN,NaN,603,True,looking cassette ac vrf residential purpose,looking for cassette ac vrf for residential pu...,AS,IL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59201,1.00,"$10,000 ~ $50,000",/Bangalore /India,ID,0.057534,22552,2023-04-28,End-Customer,New,Enterprise,...,0.0,0.064566,corporate / office,Construction,146,True,required contact number,required contact number,ID,IL
59236,0.50,NaN,//Brazil,AS,NaN,25096,2022-05-31,NaN,New,Enterprise,...,NaN,NaN,NaN,NaN,23,True,nan,nan,AS,SP
59238,0.50,NaN,/jeddah/Saudi Arabia,AS,NaN,37714,2023-04-01,End-Customer,New,SMB,...,NaN,NaN,NaN,NaN,108,True,mechanical chief xxxxx need purchase chiller v...,i am mechanical chief of the xxxxx i need purc...,AS,SJ
59248,0.25,NaN,753 Forest Street Medical/Marlborough/United ...,IT,0.642857,7576,2023-04-28,End Customer,New,SMB,...,1.0,NaN,hospital & health care,Others,589,True,nan,nan,IT,US
59249,0.25,NaN,/Salvador/Brazil,ID,NaN,25096,2021-08-10,NaN,New,Enterprise,...,NaN,NaN,NaN,NaN,211,True,nan,nan,ID,SP

In [ ]:
#transfer_date

In [ ]:
train[['expected_budget','lead_date','lead_from_channel','lead_description','event_name','prefer_ver_count','prefer_ver_mean','transfer_agreement','ver_win_rate_mean_upper']]

,expected_budget,lead_date,lead_from_channel,lead_description,event_name,prefer_ver_count,prefer_ver_mean,transfer_agreement,ver_win_rate_mean_upper
0,NaN,2022-10-15,lg.com(local),NaN,AS_IN_LG.com_I2B_2022,0.076923,0.019648,Y,1.0
1,NaN,2023-05-31,promotion page,Are there any grants for technology available?,ID_US_Createboard_Campaign,0.095436,0.067718,N,0.0
2,NaN,2023-04-19,NaN,NaN,IT_US_Cloud_IT_VMUG_UserCon_Event_Leads_230323,NaN,NaN,Y,NaN
3,"$100,000 ~ $500,000",2021-10-30,lg.com,"Dear Ladies and Gentlemen, \n\nfor three of ou...",ID_HQ_LG.com_I2B,0.095436,0.067718,Y,0.0
4,NaN,2023-04-11,lg.com(local),test,ID_SL_LG.com_I2B_Dev,NaN,NaN,Y,NaN
...,...,...,...,...,...,...,...,...,...
57060,NaN,2021-07-02,lg.com,"Please share quotation for 80"" 4k display. Ple...",ID_IL_LG.com_I2B,NaN,NaN,Y,NaN
57061,NaN,2021-07-27,lg.com,NaN,ID_SP_LG.com_I2B,NaN,NaN,Y,NaN
57062,NaN,2021-08-26,lg.com(global),how much is 5 zones ac \n1.5 hp x 4\n5 hp x 1,AS_Global_M&A_LG.com_I2B,0.269231,0.003494,Y,0.0
57063,NaN,2022-04-25,webinar(online),NaN,AS_SP_Webinar_Integrated_(220424)_Live Esquadrão,NaN,NaN,Y,NaN
57064,"less_than_£7,000",2022-09-12,facebook,NaN,IT_EU_RHQ_IFA_DualUp MNT_Lead Ads_FB,NaN,NaN,Y,NaN

### expected_budget
고객이 희망하는 예산 범위 (텍스트)

In [ ]:
train_expected_budget = train[['expected_budget']].copy()
test_expected_budget = test[['expected_budget']].copy()
train_expected_budget['expected_budget'].unique(), test_expected_budget['expected_budget'].unique()#0 ~ 1까지 0.25씩 있음

(array([nan, '$100,000 ~ $500,000', '$50,000 ~ $100,000',
        'More than $1,000,000', '$200,000 ~ $400,000', 'Less than $10,000',
        'less_than_$100,000', '$10,000 ~ $50,000', 'OnGoing',
        'Less than $100,000', '$500,000 ~ $1,000,000',
        '$100,000_-_$500,000', 'Less than $50,000',
        '500.000€__~__1.000.000€', 'more_than_$1,000,000',
        'More than $50,000', '$500,000_-_$1,000,000', 'Ongoing',
        '$200,000_~_$400,000', 'menos_de_10.000€', '$400,000 ~ $600,000',
        '$500,000 to less than $1M', '$100,000 ~ $200,000',
        'less_than_£7,000', '$100,000_~_$200,000', '€10,000_~_€50,000',
        'weniger_als_€10,000', '€100,000_~_€500,000', '€50,000_~_€100,000',
        'Menos de 10.000€', '$600,000 ~ $800,000', '$800,000 ~ $1,000,000',
        '25000 USD', 'On-going', 'more_than_£700,000',
        '$10M to less than $25M', '$10,000_~_$50,000', '$50.337.000 COP',
        '€100,000 ~ €500,000', '$400,000_~_$600,000',
        'More than $1.000.000', 'less_than_$10,000', '8.000.000 cop',
        '£7,000_~_£35,000', 'N/A;N/A', 'über_€1,000,000',
        '$600,000_~_$800,000', 'cop 5.000.000 - 9.000.000',
        '$1M to less than $10M', '700', '(Select ID_Budget)',
        '9.000.000 COP', "Don't know/Not sure", '£35,000_~_£70,000',
        '10.000€__~__50.000€', 'no know',
        '$50,000 ~ $100,000;$50,000 ~ $100,000',
        'Less than $10,000;Less than $10,000', 'Menos de $10,000',
        'Less than £7,000', 'entre_10.000€_y_50.000€',
        '$500.000 ~ $1.000.000', '€500,000_~_€1,000,000', '100000 $',
        '5000', '30.000 $ ~ 50.000 $', '1000',
        'More than $1,000,000;More than $1,000,000',
        'entre_50.000€_y_100.000€', '$50,000_~_$100,000',
        '£7,000 ~ £35,000', 'COP 2.000.000',
        '$500,000 ~ $1,000,000;$500,000 ~ $1,000,000',
        '$100,000 ~ $500,000;$100,000 ~ $500,000',
        'Entre 50.000€ y 100.000€', 'Residential (Home)',
        'R$100.000 ~ R$500.000', 'cop 5.000.000', 'budget',
        '£70,000_~_£350,000', 'Weniger als €10,000',
        '10.000.000 - 20.000.000', 'Less than IDR 155,000,000', '0',
        '€ 5000,00', 'Entre 10.000€ y 50.000€', '10.000 $ ~ 50.000 $',
        '$800,000_~_$1,000,000', '$10,000 ~ $50,000;$10,000 ~ $50,000',
        'cop 3.000.000', 'More than $123,000', 'Less than $123,000',
        'entre_500.000€_y_1.000.000€', 'More than $100,000',
        '$50.000 - $10.000', 'cop 15.000.000 - 30.000.000'], dtype=object),
 array([nan, 'Less than $10,000', '$10,000 ~ $50,000', 'OnGoing',
        '$400,000 ~ $600,000', '$50,000 ~ $100,000',
        'More than $1,000,000', '$200,000 ~ $400,000',
        '$100,000 ~ $200,000', '$800,000 ~ $1,000,000',
        '$600,000 ~ $800,000', 'less_than_$10,000', 'Less than $50,000',
        '$10,000_~_$50,000', 'more_than_$1,000,000', '$400,000_~_$600,000',
        'Less than $100,000',
        '$500,000 ~ $1,000,000;$500,000 ~ $1,000,000',
        '$500,000 ~ $1,000,000', '$200,000_~_$400,000',
        '$100,000 ~ $500,000'], dtype=object))

# lead_date
Lead 정보 생성일

In [ ]:
train_lead_date = train[['lead_date']].copy()
test_lead_date = test[['lead_date']].copy()
train_lead_date['lead_date'].unique(), test_lead_date['lead_date'].unique()#0 ~ 1까지 0.25씩 있음

(array(['2022-10-15', '2023-05-31', '2023-04-19', '2021-10-30',
        '2023-04-11', '2022-11-08', '2022-05-12', '2022-04-17',
        '2023-03-01', '2023-01-10', '2023-05-24', '2023-03-31',
        '2021-05-13', '2022-06-08', '2022-04-18', '2021-05-27',
        '2023-01-24', '2022-02-18', '2022-08-18', '2022-03-16',
        '2023-01-21', '2023-02-10', '2022-06-28', '2022-06-30',
        '2022-05-03', '2022-05-21', '2023-04-27', '2023-05-29',
        '2023-02-11', '2022-02-25', '2023-05-18', '2022-04-09',
        '2022-05-11', '2022-02-13', '2022-05-10', '2022-06-13',
        '2021-11-26', '2023-05-21', '2022-05-06', '2022-11-29',
        '2023-04-28', '2023-03-17', '2023-02-28', '2021-12-27',
        '2023-01-26', '2022-01-14', '2023-02-15', '2022-12-16',
        '2022-06-11', '2022-10-30', '2021-08-05', '2022-03-29',
        '2022-07-05', '2023-03-04', '2022-07-19', '2022-09-20',
        '2023-01-18', '2023-04-08', '2023-04-20', '2022-11-26',
        '2022-04-26', '2023-01-07', '2022-03-01', '2021-04-14',
        '2022-11-22', '2023-04-06', '2022-09-11', '2022-01-23',
        '2022-07-27', '2022-12-27', '2023-04-10', '2022-11-17',
        '2021-09-18', '2022-05-26', '2023-05-09', '2021-05-01',
        '2023-05-11', '2021-10-18', '2021-06-04', '2022-08-09',
        '2021-12-28', '2022-01-19', '2022-10-28', '2022-12-22',
        '2021-11-30', '2022-01-08', '2022-11-16', '2022-05-25',
        '2022-09-15', '2023-04-05', '2022-06-29', '2022-04-29',
        '2022-02-03', '2023-04-21', '2023-04-22', '2021-09-27',
        '2022-08-14', '2022-05-13', '2022-09-19', '2023-01-20',
        '2023-05-15', '2023-03-08', '2022-11-01', '2022-08-30',
        '2022-08-27', '2022-12-13', '2022-10-04', '2021-06-23',
        '2023-03-30', '2022-04-27', '2022-11-10', '2022-12-15',
        '2022-10-24', '2023-05-05', '2022-12-29', '2022-04-07',
        '2021-09-15', '2022-07-30', '2022-02-15', '2022-07-26',
        '2022-09-16', '2022-01-01', '2022-09-27', '2022-11-12',
        '2022-04-22', '2022-12-20', '2022-04-08', '2022-01-28',
        '2022-02-26', '2021-10-21', '2022-04-13', '2023-04-14',
        '2022-01-26', '2023-05-17', '2022-05-04', '2021-09-28',
        '2023-01-14', '2023-05-27', '2022-05-07', '2022-06-04',
        '2023-05-26', '2022-04-11', '2022-07-06', '2022-08-10',
        '2022-07-13', '2022-11-14', '2021-10-15', '2021-04-28',
        '2023-03-24', '2021-06-11', '2021-03-11', '2022-06-02',
        '2021-08-13', '2022-11-07', '2022-08-23', '2022-09-07',
        '2022-09-02', '2023-01-23', '2023-03-28', '2021-10-05',
        '2022-02-11', '2022-08-19', '2022-05-05', '2022-02-22',
        '2021-07-24', '2021-08-24', '2023-03-12', '2023-04-01',
        '2021-09-21', '2022-11-04', '2023-02-07', '2022-05-29',
        '2021-07-30', '2022-12-21', '2022-04-24', '2022-02-10',
        '2022-09-09', '2023-01-25', '2021-08-02', '2021-09-17',
        '2021-06-24', '2023-01-31', '2021-09-01', '2023-02-01',
        '2023-04-04', '2023-02-03', '2023-03-09', '2022-11-03',
        '2022-06-03', '2022-10-21', '2022-10-05', '2022-12-10',
        '2023-02-23', '2022-08-28', '2022-05-23', '2022-04-14',
        '2022-02-02', '2022-04-28', '2022-09-30', '2022-12-23',
        '2022-06-25', '2022-04-23', '2022-10-25', '2021-08-21',
        '2021-12-10', '2021-08-15', '2022-07-01', '2022-01-20',
        '2021-11-16', '2023-05-12', '2021-12-08', '2023-04-29',
        '2022-05-30', '2021-04-08', '2021-08-26', '2022-02-16',
        '2023-01-06', '2022-07-07', '2023-02-12', '2021-11-02',
        '2021-09-29', '2022-11-30', '2022-01-27', '2023-04-26',
        '2022-12-09', '2023-02-04', '2022-10-01', '2022-12-14',
        '2021-11-24', '2022-09-01', '2023-04-23', '2022-06-09',
        '2022-05-20', '2023-01-03', '2021-06-26', '2023-05-06',
        '2022-12-02', '2021-04-27', '2021-11-14', '2023-02-06',
        '2022-07-03', '2021-11-18', '2023-03-18', '2022-07-14',
        '2022-09-22', '2022-05-02', '2021-03-31', '2021-12-19',
        '2023-02-24', '2021-08-09', '2022-04-06', '2021-12-18',
        '2023-02-22', '2023-02-05', '2022-12-26', '2022-02-27',
        '2022-06-12', '2021-06-21', '2021-08-03', '2021-12-15',
        '2022-10-12', '2021-09-03', '2022-10-07', '2022-09-06',
        '2022-04-02', '2021-12-24', '2022-06-17', '2022-11-21',
        '2022-03-10', '2023-05-20', '2023-05-01', '2022-05-28',
        '2022-12-06', '2021-05-28', '2022-12-17', '2022-07-22',
        '2023-01-27', '2022-03-22', '2022-10-08', '2022-08-29',
        '2021-07-16', '2022-09-17', '2022-12-24', '2022-11-13',
        '2022-09-05', '2021-06-01', '2023-01-05', '2023-04-25',
        '2022-03-21', '2023-03-07', '2023-01-04', '2021-09-19',
        '2022-10-20', '2022-03-26', '2023-03-06', '2022-06-01',
        '2021-11-20', '2022-02-19', '2022-06-15', '2023-05-25',
        '2022-08-12', '2021-11-19', '2022-05-14', '2022-07-20',
        '2021-03-29', '2022-10-16', '2022-11-18', '2021-11-05',
        '2021-08-31', '2023-03-21', '2022-05-17', '2022-12-11',
        '2023-02-19', '2022-09-13', '2022-08-16', '2022-03-18',
        '2021-05-25', '2023-03-10', '2022-09-25', '2021-04-21',
        '2021-04-07', '2021-10-16', '2022-06-10', '2022-03-11',
        '2022-10-06', '2021-07-02', '2022-08-24', '2022-08-25',
        '2022-07-31', '2023-03-23', '2023-03-02', '2021-10-20',
        '2023-02-17', '2022-01-30', '2023-01-01', '2022-05-19',
        '2023-04-07', '2021-10-22', '2022-12-25', '2021-09-02',
        '2023-03-16', '2021-07-19', '2022-09-28', '2022-07-21',
        '2022-10-31', '2023-02-20', '2022-02-12', '2021-06-27',
        '2021-10-08', '2023-04-17', '2023-01-17', '2022-09-14',
        '2021-09-23', '2021-12-04', '2022-10-26', '2022-04-25',
        '2023-03-29', '2023-03-25', '2022-02-09', '2021-11-23',
        '2022-07-28', '2022-06-16', '2021-12-25', '2021-12-31',
        '2021-12-13', '2022-09-23', '2022-03-17', '2022-08-31',
        '2021-06-16', '2021-05-20', '2023-05-10', '2022-11-09',
        '2021-09-13', '2021-04-20', '2022-06-18', '2022-11-25',
        '2023-04-12', '2023-04-13', '2021-12-16', '2023-03-19',
        '2021-06-19', '2021-05-31', '2021-06-08', '2023-05-02',
        '2023-02-09', '2021-08-28', '2022-03-23', '2022-01-13',
        '2022-06-07', '2023-02-18', '2022-11-24', '2023-02-14',
        '2023-01-11', '2021-11-08', '2021-04-19', '2022-09-12',
        '2021-07-13', '2022-06-22', '2022-10-27', '2022-02-01',
        '2021-09-08', '2022-01-29', '2022-01-05', '2021-08-04',
        '2021-08-10', '2022-09-10', '2022-12-19', '2022-04-10',
        '2022-04-12', '2022-12-30', '2023-05-03', '2022-12-01',
        '2022-09-29', '2022-12-28', '2022-05-15', '2022-05-27',
        '2023-05-23', '2022-05-31', '2023-05-16', '2021-09-24',
        '2022-11-11', '2022-06-05', '2023-05-14', '2022-03-28',
        '2022-12-31', '2021-03-24', '2022-09-08', '2022-05-22',
        '2022-11-05', '2021-09-22', '2022-11-23', '2021-10-27',
        '2021-08-25', '2021-06-02', '2022-08-20', '2021-12-01',
        '2022-12-07', '2021-06-17', '2023-03-22', '2022-03-04',
        '2021-07-07', '2022-08-02', '2021-12-09', '2021-10-12',
        '2022-07-24', '2023-04-15', '2022-04-01', '2022-08-11',
        '2022-02-20', '2022-03-30', '2021-08-07', '2023-02-26',
        '2022-02-24', '2021-10-14', '2022-10-19', '2022-09-26',
        '2023-01-28', '2022-04-21', '2022-02-23', '2021-08-17',
        '2021-12-03', '2022-07-23', '2022-04-03', '2022-10-11',
        '2022-03-14', '2021-11-11', '2023-01-13', '2023-04-18',
        '2021-07-21', '2021-05-07', '2022-09-21', '2023-02-16',
        '2023-03-05', '2022-06-14', '2023-01-12', '2023-02-02',
        '2022-07-25', '2021-06-09', '2022-01-21', '2022-04-15',
        '2022-11-27', '2022-09-24', '2021-11-21', '2022-09-04',
        '2022-06-24', '2022-03-27', '2023-05-22', '2021-11-15',
        '2022-11-19', '2022-04-05', '2022-04-16', '2021-12-07',
        '2021-11-13', '2021-09-10', '2021-04-15', '2023-05-04',
        '2021-10-01', '2022-03-25', '2023-03-14', '2023-05-19',
        '2021-09-05', '2023-05-28', '2023-02-21', '2023-04-30',
        '2021-06-20', '2022-02-04', '2022-05-24', '2022-10-22',
        '2022-01-06', '2022-11-28', '2021-10-02', '2021-10-09',
        '2021-06-06', '2022-03-24', '2023-03-20', '2022-05-09',
        '2022-08-17', '2022-06-26', '2022-03-08', '2022-02-17',
        '2022-02-14', '2023-01-30', '2022-07-15', '2022-01-31',
        '2023-05-08', '2022-03-06', '2022-05-08', '2021-08-23',
        '2022-02-07', '2021-07-08', '2023-05-13', '2021-10-03',
        '2021-11-25', '2022-01-17', '2021-07-20', '2022-03-31',
        '2023-03-03', '2021-05-16', '2022-01-18', '2021-06-30',
        '2022-11-06', '2021-07-25', '2023-02-08', '2023-03-11',
        '2022-08-01', '2023-02-25', '2023-01-19', '2021-10-07',
        '2021-12-30', '2022-03-09', '2021-05-04', '2022-01-11',
        '2022-08-22', '2022-03-05', '2023-03-27', '2022-04-19',
        '2023-01-29', '2021-10-13', '2021-12-17', '2021-12-23',
        '2021-07-10', '2021-12-14', '2023-03-15', '2021-03-17',
        '2021-09-11', '2021-11-27', '2021-05-02', '2022-01-25',
        '2022-10-02', '2022-03-12', '2022-08-13', '2022-06-20',
        '2022-07-17', '2022-01-07', '2021-12-29', '2022-06-21',
        '2021-09-30', '2022-02-08', '2022-12-08', '2023-05-07',
        '2022-10-14', '2021-07-06', '2023-01-09', '2022-10-09',
        '2021-08-12', '2023-02-13', '2022-06-19', '2021-06-15',
        '2023-04-03', '2021-03-12', '2023-04-02', '2022-12-04',
        '2022-07-10', '2021-10-23', '2021-11-12', '2021-11-22',
        '2021-12-26', '2022-03-15', '2021-08-06', '2023-04-16',
        '2021-06-22', '2021-10-31', '2023-04-24', '2022-07-09',
        '2021-06-07', '2022-11-20', '2022-08-26', '2022-03-03',
        '2022-09-18', '2022-06-06', '2022-07-12', '2021-09-26',
        '2021-09-25', '2021-03-30', '2022-07-29', '2022-03-19',
        '2021-04-03', '2023-04-09', '2022-07-18', '2021-10-26',
        '2021-04-24', '2022-10-23', '2022-03-07', '2021-07-01',
        '2021-07-26', '2022-08-21', '2021-12-11', '2022-01-10',
        '2022-12-18', '2021-07-29', '2022-04-20', '2021-11-03',
        '2021-09-04', '2021-04-04', '2021-08-14', '2021-11-06',
        '2021-11-17', '2022-11-15', '2022-12-03', '2022-01-15',
        '2022-01-12', '2022-05-18', '2021-06-10', '2023-02-27',
        '2023-01-02', '2023-03-26', '2021-10-06', '2022-07-02',
        '2023-05-30', '2021-09-14', '2022-08-03', '2022-10-13',
        '2021-08-19', '2022-10-17', '2021-06-18', '2021-04-22',
        '2021-09-12', '2022-06-27', '2021-04-30', '2021-09-16',
        '2022-02-28', '2021-10-28', '2022-05-16', '2021-04-11',
        '2021-05-29', '2021-04-01', '2021-07-23', '2022-07-08',
        '2021-09-07', '2021-07-09', '2023-01-08', '2021-04-12',
        '2022-06-23', '2021-07-15', '2022-04-04', '2021-03-16',
        '2021-05-15', '2021-10-17', '2022-09-03', '2021-11-01',
        '2021-12-06', '2023-01-15', '2021-10-11', '2021-07-17',
        '2021-09-06', '2021-05-14', '2022-01-04', '2021-10-24',
        '2022-03-02', '2021-10-25', '2021-08-20', '2021-03-22',
        '2021-03-14', '2021-07-03', '2021-07-22', '2021-10-29',
        '2021-08-30', '2022-03-13', '2022-10-10', '2023-03-13',
        '2021-12-21', '2022-08-15', '2021-03-19', '2021-12-22',
        '2022-10-29', '2021-06-03', '2022-01-09', '2022-01-16',
        '2021-11-28', '2021-08-29', '2021-04-13', '2021-12-02',
        '2022-01-03', '2022-07-16', '2022-12-05', '2022-01-24',
        '2021-11-10', '2021-04-18', '2021-12-20', '2022-02-05',
        '2021-09-09', '2021-08-27', '2021-04-16', '2021-08-18',
        '2021-05-24', '2021-12-12', '2021-08-11', '2021-04-17',
        '2021-06-12', '2021-07-12', '2021-06-05', '2021-11-04',
        '2021-01-01', '2021-04-29', '2021-03-18', '2021-05-17',
        '2021-07-05', '2021-05-21', '2021-10-19', '2022-12-12',
        '2021-05-26', '2021-05-18', '2021-05-11', '2021-05-09',
        '2021-08-08', '2023-01-16', '2022-02-21', '2021-08-22',
        '2021-11-09', '2023-01-22', '2021-04-06', '2021-04-23',
        '2021-05-08', '2021-05-10', '2021-07-27', '2021-03-25',
        '2022-01-02', '2021-04-09', '2021-10-04', '2021-04-10',
        '2021-07-31', '2021-04-25', '2021-06-14', '2021-10-10',
        '2021-06-13', '2021-07-28', '2021-12-05', '2021-05-23',
        '2021-07-18', '2021-07-04', '2022-07-11', '2021-11-29',
        '2021-11-07', '2021-09-20', '2022-11-02', '2021-06-29',
        '2021-07-11', '2021-05-03', '2022-07-04', '2021-08-16',
        '2021-03-15', '2021-05-22', '2021-06-28', '2021-04-26',
        '2022-02-06', '2022-05-01', '2021-01-08', '2021-01-22',
        '2021-02-06', '2022-04-30', '2022-08-08', '2021-05-30',
        '2021-05-19', '2021-04-02'], dtype=object),
 array(['2023-07-12', '2023-08-05', '2023-08-20', '2023-06-20',
        '2023-06-08', '2023-08-02', '2023-10-06', '2023-10-24',
        '2023-08-25', '2023-07-08', '2023-09-12', '2023-06-19',
        '2023-08-23', '2023-07-18', '2023-09-18', '2023-10-21',
        '2023-07-05', '2023-09-22', '2023-08-31', '2023-08-29',
        '2023-06-22', '2023-08-09', '2023-07-10', '2023-06-11',
        '2023-09-28', '2023-06-09', '2023-09-09', '2023-09-07',
        '2023-07-31', '2023-07-16', '2023-06-27', '2023-09-15',
        '2023-09-08', '2023-07-15', '2023-10-05', '2023-07-07',
        '2023-06-14', '2023-09-20', '2023-07-26', '2023-09-02',
        '2023-09-01', '2023-07-21', '2023-08-18', '2023-08-10',
        '2023-09-16', '2023-07-28', '2023-06-15', '2023-07-25',
        '2023-09-25', '2023-08-24', '2023-10-07', '2023-09-24',
        '2023-06-30', '2023-08-07', '2023-08-08', '2023-09-13',
        '2023-06-10', '2023-09-19', '2023-07-22', '2023-08-03',
        '2023-07-11', '2023-08-19', '2023-07-13', '2023-08-12',
        '2023-10-10', '2023-10-20', '2023-06-24', '2023-09-14',
        '2023-09-23', '2023-08-13', '2023-07-01', '2023-07-29',
        '2023-10-12', '2023-07-17', '2023-09-27', '2023-10-26',
        '2023-06-02', '2023-07-27', '2023-08-04', '2023-09-05',
        '2023-07-04', '2023-10-04', '2023-09-04', '2023-06-21',
        '2023-06-26', '2023-08-14', '2023-07-23', '2023-06-01',
        '2023-06-04', '2023-06-16', '2023-06-06', '2023-07-19',
        '2023-10-08', '2023-06-07', '2023-09-26', '2023-06-13',
        '2023-08-22', '2023-07-20', '2023-06-12', '2023-06-05',
        '2023-06-28', '2023-08-30', '2023-08-21', '2023-09-17',
        '2023-09-30', '2023-10-11', '2023-06-17', '2023-07-03',
        '2023-07-14', '2023-10-01', '2023-08-16', '2023-06-18',
        '2023-10-16', '2023-08-27', '2023-09-29', '2023-08-15',
        '2023-06-23', '2023-06-03', '2023-09-10', '2023-10-25',
        '2023-10-17', '2023-08-06', '2023-09-03', '2023-10-14',
        '2023-10-22', '2023-07-06', '2023-07-24', '2023-10-19',
        '2023-06-25', '2023-07-02', '2023-09-11', '2023-08-28',
        '2023-08-01', '2023-10-03', '2023-10-15', '2023-07-30',
        '2023-08-26', '2023-10-27', '2023-08-11', '2023-06-29',
        '2023-07-09', '2023-08-17', '2023-09-06', '2023-10-09',
        '2023-10-18', '2023-10-13', '2023-10-02', '2023-10-23'],
       dtype=object))

### lead_from_channel
Lead 정보가 수집된 채널 이름 (lg.com, 페이스북, 웨비나 등 다양한 채널을 통해서 수집)

In [ ]:
train_lead_from_channel = train[['lead_from_channel']].copy()
test_lead_from_channel = test[['lead_from_channel']].copy()
train_lead_from_channel['lead_from_channel'].unique(), test_lead_from_channel['lead_from_channel'].unique()#0 ~ 1까지 0.25씩 있음

(array(['lg.com(local)', 'promotion page', nan, 'lg.com', 'lg.com(global)',
        'facebook', 'c-display', 'brochure & leaflet', 'webinar(online)',
        'microsite', 'youtube', 'instagram', 'webinar', 'gdn', 'linkedin',
        'newsletter(+blogsubscription)', 'exhibition', 'seminar', 'etc.',
        'roadshow', 'digital showroom', 'sem', 'website', 'dealertrip',
        'eloqua', 'sub(webpage)', 'conference', 'casa mollde',
        '[mql] fs_id_standard signage_20211025',
        'eu_es_id_202012w4_sem hotels', 'db(imported)', 'micrositio',
        'casa cor exhibition', '[mql] fs_id_hotel tv_20211011',
        'newsletter', 'db (imported)', 'offlineevent',
        'eu_es_id_202012w4_led campaign', 'equipotel event',
        '[mql]vh_lgsafepass_20210915',
        'id_bn_controlroomwhitepaperform_210707', 'lsvp',
        '[mql]vh_lgsafepass_20210908', '[mql]vh_lgsafepass_20210909',
        '[mql] fs_id_led signage_20211026', 'information.display@lge.pl',
        '[mql] fs_id_email_20210609', '[mql]vh_lgsafepass_20210914',
        'eu_es_id_202101w1_sem hotels', 'seminar(offline)',
        'eu_es_id_202101w3_local website', 'equipotel fair',
        'eu_es_id_202102w1_local website', 'sheila datz',
        '[mql] fs_id_window facing_20211117', 'lg.co',
        '[mql] fs_id_laec015_20211015', 'gsfs', 'exhibiton',
        'ifa dualup 2022', '[mql] fs_id_video wall signage_20211021',
        '[mql] fs_id_lgoledr_20211001', 'eu_es_id_202101w1_led campaign'],
       dtype=object),
 array(['[premql]us_id__20230701', 'lg.com(local)', 'facebook', 'webinar',
        'promotion page', nan, 'seminar', 'exhibition',
        'newsletter(+blogsubscription)', 'youtube', 'linkedin', 'sem',
        'db(imported)', 'brochure & leaflet', 'conference',
        'lg.com(global)', 'microsite', 'lsvp', 'gdn', 'sub(webpage)',
        'dealertrip', 'etc.', 'partner portal', 'roadshow', 'instagram',
        'lg.com', 'faceook', '[premql]sp_id__20230630', 'webinar(online)',
        '[premql]pr_id_facebook_20230702', 'lge.co.kr', 'zoominfo',
        '[premql]pr_id_facebook_20230701'], dtype=object))

### lead_description
객이 작성한 Lead Description 텍스트

In [ ]:
train_lead_description = train[['lead_description']].copy()
test_lead_description = test[['lead_description']].copy()
train_lead_description['lead_description'].unique(), test_lead_description['lead_description'].unique()#0 ~ 1까지 0.25씩 있음

(array([nan, 'Are there any grants for technology available?',
        'Dear Ladies and Gentlemen, \n\nfor three of our grading suites, we need a quotation for three XXXXX UltraFine OLED Pro 65EP5G Display.\n\nIt would be nice, if you can get in touch with me as soon as possible. \n\nKind regards\nThorsten Rosche',
        ..., 'for 12 th physics classroom',
        'Please share quotation for 80" 4k display. Please share email id fo sales person to enable to share detailed specification and qty.',
        'how much is 5 zones ac \n1.5 hp x 4\n5 hp x 1'], dtype=object),
 array([nan, 'i have an old system need to be replaced',
        'WE WANT TO PURCHASE , WHICH WILL BE COMPATIBLE OF 2-3 INDOOR AND ONE OUTDOOR',
        ...,
        'Interested to purchase Multo split for home, we have to plan install total 8 Nos X 1.5 ton and 2 nos X 2 ton and 2 nos X 1 ton air conditioner, Kindly give a quotation for the multi split system',
        "Voltage and Harmonic issues caused by VFD's in ARUM241CTE5 and ARUM192CTE5 (32 Total). Many compressors, VFD's and circuits boards have shorted. (XXXXX)  Need to size line reactors to correct harmonics issues.  Need consultation to size properly. Not sure if units have (2) internal VFD's controlling (1) compressor each. Or, (1) internal VFD controlling (2) compressors.  Note XXXXX technicians have come from Korea to investigate initially, results where unconclusive. I have found the power quality issue and I need to address with you ASAP.",
        'Hi,  I would like to request for quotation for equipments for on going project . I have list of the equipments.'],
       dtype=object))

### event_name
영업 활동이 있었던 마케팅 이벤트

In [ ]:
train_event_name = train[['event_name']].copy()
test_event_name = test[['event_name']].copy()
train_event_name['event_name'].unique(), test_event_name['event_name'].unique()

(array(['AS_IN_LG.com_I2B_2022', 'ID_US_Createboard_Campaign',
        'IT_US_Cloud_IT_VMUG_UserCon_Event_Leads_230323', ...,
        'IT_MS_LG.com_I2B_Cloud',
        'AS_PH_Seminar_GL_210617_LGUniqueSpecifications_Attendee_form',
        'IT_Showroom_Medical(Demo Req)'], dtype=object),
 array(['ID_US_Event_COCC Partners Expo_20230614', 'AS_IL_LG.com_I2B_2022',
        'AS_EG_facebookleadscampaign_May2023', 'ID_IL_LG.com_I2B',
        'AS_SP_Webinar_Integrated_SeminarDate(220322)_CasaConteúdo',
        'calendario_completo_septiembre_2023', 'ID_US_MAGNIT-Site Survey',
        'ID_HQ_Education_Lead Campaign_Facebook',
        'ID_MEAHQ Sales Contact QR Code_Aug2023',
        'IT_US_Event_SHI EUC Summit_20230620',
        'AS_EG_Multi V Residential Campaign_Facebook_2021',
        'AS_TK_LG.com_I2B_2022', 'AS_EG_LG.com_I2B',
        'AS_PH_Seminar_REGISTRATION_Incl_MQLs_form_September 2023',
        'AS_EG_LG.com_I2B_2022_Ara', 'AS_SP_LG.com_I2B_2022',
        'ID_MS_Promos_AGO', 'AS_SP_Evento FEBRAVA_230914',
        'AS_SP_Cursos Online_Março', 'curso_online_calendario',
        'IT_US_Event_SHI Booth ISTE_20230628',
        'ID_IL_LN IDB (JUNE) Lead Campaign_230601',
        'ID_LATAM_LED Control Room_Google Paid Campaign_2023',
        'Cursos Online Junio 2023', 'AS_SP_Evento FEBRAVA',
        'IT_US_Event_Gotham Summer ETE 2023',
        'ID_US_Event_ISTE2023_20230623',
        'AS_IS_Launching_200923_MULTIVi_Padova_Registration_form',
        'ID_IL_FB IDB (SEP) Retargeting_230901', 'ID_AR_LG.com_I2B',
        'ID_IL_FB IDB (JUNE) Retargeting_230601', 'cursos_online_julio',
        'AS_SP_Seminar_(13092023)_Febrava', 'ID_MS_INFOCOMM_JUN',
        'ID_AP_EduTECH_20230825',
        'AS_IL_Architect_Consultant_Multi_i_GL_20230713_Registration form',
        'ID_US_Eloqua_QSRAlwaysOn', 'ID_SA_LG.com_I2B',
        'ID_IL_FB IDB (AUG) Retargeting_230801',
        'AS_PH_Seminar_REGISTRATION_Incl_MQLs_form_May 2023',
        'AS_IN_NURTURING_CONTENT_DOWNLOAD', 'AS_PL_LG.com_I2B_2022',
        'ID_IL_FB IDB (JULY) Lead Campaign_230701',
        'AS_EG_Students_Seminar Registration Form 2023',
        'ID_AP_LG.com_I2B', 'ID_SP_LG.com_I2B',
        'IT_EU RHQ_medON Technical Training_230919',
        'AS_MK_BUL_Heating_Rolling_Seminar_20231012_StaraZagora_EXP',
        'AS_DG_Webinar2023',
        'AS_SL_Launching_100823_NPI Multi V i Product Launch_Registration_form',
        '202006_SCA_MS_Webinar', 'ID_MS_LG.com_I2B', nan,
        'AS_SP_Evento FEBRAVA_Esquadrão_230914',
        'ID_IL_FB IDB (JUNE) Lead Campaign_230601',
        'AS_SP_Seminar_230804_LATS CAD', 'AS_Global_Asia_LG.com_I2B',
        'ID_US_LG.com_ecommerce', 'ID_HQ_Cdisplay_I2B',
        'AS_SP_Cursos Online', 'ES_LGPEC', 'ID_CB_LG.com_I2B_Spa',
        'IT_US_Event_Citrix IGEL Unite Lunch and Learn_20230613',
        'LSVP(Digital Signage)', 'ID_LATAM_Facebook_IDB Education_2023',
        'IT_US_Event_VMware Explore 2023 ControlUp Party_20230822',
        'IT_MS_LG.com_I2B_Monitor&Other', 'ID_HQ_LG.com_I2B',
        'AS_SL_Multi V i_Presentation_270923', 'AS_PH_LG.com_I2B_2022',
        'ID_PR_AIO_SorteoCommTV_June&July',
        'AS_Global_North America_LG.com_I2B', 'AS_SP_Expedição',
        'AS_SJ_LG.com_I2B_Eng', 'ID_US_Eloqua_AlwaysOn',
        'ID_TK_LG.com_I2B', 'AS_CB_LG.com_I2B_2022',
        'AS_IS_Scaldacqua_230519',
        'AS_GF_Oman_Sohar_Registrationform_20230727',
        'AS_HS_Profiling Program Form_230823', 'ID_US_LG.com_I2B',
        'AS_IL_D-Arch_Build_Delhi_June(230623)_Attendee_form',
        'ID_GF_LG.com_I2B',
        'AS_SP_EVENTO FEBRAVA ESQUADRÃO_230913_Confirmation',
        'ID_HQ_Virtual Production_Lead Campaign_Facebook',
        'Calendario_cursos_online_October_2023', 'ID_MS_LEDSignage_MAY',
        'ID_LATAM_Facebook_IDB Corporate_2023',
        'ID_IL_FB IDB (AUG) Lead Campaign_230801', 'US_ESS_TradeShow',
        'AS_CL_LG.com_I2B_2022',
        'ID_IL_LN IDB (JULY) Lead Campaign_230701', 'curso_online_LATS',
        'AS_BN_LG Klimaat_ContactForm_Warmtepomp_20230523',
        'ID_US_EDU_Brand_Ambassador_20230531', 'AS_AF_LG.com_I2B',
        'AS_IS_Launching_290923_MULTIVi_Milano_Registration_form',
        'AS_TH_Dealer Trip_20231006', 'AS_TH_LG.com_I2B_2022',
        'AS_HS_Seminar_190723_Multi V i_Statheros_MQL attendee form',
        'AS_SL_VRF_Split_System_Training_20230824',
        'ID_US_Eloqua_HospitalityAlwaysOn',
        'ID_IL_FB IDB (SEP) Lead Campaign_230901', 'ID_SJ_LG.com_I2B_Eng',
        'LSVP(LED Only)', 'curso_online_repeticion_JUL',
        'IT_UK_LG.com_I2B_Monitor&Other',
        'AS_IN_DealerGathering_Surabaya_20230908', 'ID_MS_DigitalAO_JUL',
        'SP_ID_Events', 'ID_IL_LN IDB (SEP) Lead Campaign_230901',
        'ID_HQ_CDisplay_DC_I2B', 'AS_VH_LG.com_I2B_2022',
        'ID_UK_LG.com_I2B', 'AS_IN_DealerGathering_Jakarta_20230808',
        'AS_IS_Launching_200925_MULTIVi_Roma_Registration_form',
        'IT_CB_LG.com_I2B_Monitor&Other', 'AS_US_LIVE_LGHVAC Contact Us',
        'AS_YK_LG.com_I2B_2022', 'IT_Digital_Showroom_Cloud_Global',
        'ID_SP_SImeeting_2023', 'ID_US_Eloqua_MedicalAlwaysOn_20230503',
        'AS_SP_Evento FEBRAVA_Van', 'AS_AR_LG.com_I2B_2022',
        'ID_MEAHQ Sales Contact QR Code_Sep2023',
        'AS_TH_Nurturing_Content download_request_Refrigerant Pipe_Thai',
        'ID_US_Event_Hitec Toronto_20230629',
        'AS_IS_RAC Campaign - 230619', 'detección_de_fuga_vrf',
        'AS_MS_LG.com_I2B_2022', 'AS_EG_Seminar_230919',
        'IT_MK_LG.com_I2B_Monitor&Other', 'AS_UK_LG.com_I2B',
        'AS_IL_MumbaiSERVICESEMINAR_Integrated_June(230616)_Attendee_form',
        'AS_IS_Launching_270923_MULTIVi_Napoli_Registration_form',
        'ID_CL_LG.com_I2B',
        'AS_IL_DUBAI_GL_20220729_Qualifiers_Registration form_ChannelPartners',
        'AS_PH_Seminar_REGISTRATION_Incl_MQLs_form_August 2023',
        'IT_IL_LG.com_I2B_Laptop',
        'ID_US_lg.com_direct-view-led-ultimate-business-display',
        'AS_IS_Form_MULTIVi_Torino_LaunchingEvent_261023',
        'ID_PR_AIO Paid Campaign_Facebook_July 2023',
        'ID_US_Createboard_Campaign',
        'ID_MEAHQ Sales Contact QR Code_Jul2023',
        'IT_US_Event_Northeast XL CUGC_20230621',
        'ID_IL_FB IDB (JULY) Retargeting_230701',
        'AS_EG_B2Bfbleadsgeneration_June-Aug-2022-EN',
        'ID_AR_Partner Form_2023', 'HQ_Change_Consent_Modify',
        'ID_US_Hospitality_Nurture_20230216',
        'IT_HQ_Campaign_20 1st Digital Campaign (7.23-29/ 영,독,스,네/ 34CN650, 24CK560)',
        'AS_TH_Academy Registration_20230515', 'LGMV_CURSO_SEPTIEMBRE',
        'IT_Digital_Showroom_Medical_Global', 'FAQ_controles',
        'AS_IN_MULTI V I LAUNCHING_20230622',
        'AS_SP_Seminar_(12092023)_Febrava',
        'AS_MK_Profiling Program Form_20230519_ENG',
        'AS_PS_Webinar_221124_GoToWebinar_registration',
        'AS_LF_LG.com_I2B_Eng_2022',
        'ID_EU_RHQ_IBC2023_E-Zone_media_braodcast_230919',
        'ID_IL_LN IDB (AUG) Lead Campaign_230801', 'AS_AP_LG.com_I2B',
        'IT_DG_LG.com_I2B_Monitor&Other',
        'AS_TH_Service seminar_140723_Register_EN/TH',
        'AS_Global_M&A_LG.com_I2B', 'AS_GF_LG.com_I2B_Eng',
        'AS_HS_Seminar_050723_Multi V i_Tolias_form',
        'ID_ES_SiliconPodcast_Education',
        'AS_IN_EngineerSeminar_Bandung_20230926',
        'AS_IN_AcademyTraining_Jakarta_Sept2023', 'OnSite_June',
        'AS_Global_HVACDesignAward_application_form_2023',
        'AS_CI_LG.com_I2B_Eng_2022', 'ID_PS_LG.com_I2B',
        'AS_IN_NURTURING_IAQ-ERV_2023', 'ID_PR_ExpoDeco Event_August 2023',
        'AS_SP_Webinar_(310523)_TeaTime ABCD', 'ID_MS_VideoWall_AGO',
        'ID_US_Eloqua_MedicalAlwaysOn',
        'ID_IL_FB IDB (OCT) Lead Campaign_231001',
        'ID_PH_20230510_PC:DRoadshowBoracay_BITA_Registration',
        'ID_HQ_LSVP_I2B_Live', 'SINGLE_CAC',
        'AS_PH_Seminar_REGISTRATION_Incl_MQLs_form_June 2023',
        'AS_SP_Seminar_Nurturing_Content download_request_form',
        'LGBSC_BUSINES_CASE_NEWSLETTER', 'AS_Global_Europe_LG.com_I2B',
        'AS_SP_Evento FEBRAVA_2',
        'AS_MK_SRB_Heating_Rolling_Seminar_20231006_Niš_EXP',
        'IT_PR_LG.com_I2B_Medical',
        'AS_GF_Oman_Nizwa_Registrationform_20230726',
        'AS_HS_Seminar_260923_AWHP_Faklaris_MQL attendee form',
        'IT_Global_LG.com_I2B_Monitor&Other',
        'AS_SP_Evento FEBRAVA_Esquadrão_230915',
        'AS_GF_Qatar_FocusStudio_Registrationform_20230814',
        'AS_SP_LATS REVIT_Avaliacao', 'IT_US_LG.com_I2B',
        'AS_MK_LG.com_I2B_2022', 'Expo AHR 2023_LGEMS',
        'AS_SL_DealerTrip_050623_ThailandTrip_form_MQL',
        'ID_VH_Campaign Acquisition_Y2023',
        'Facebook_Campaign_SingleSplit_CAC_Lead',
        'AS_HQ_EventType_EventStartDate(DDMMYY)_EventName_form_MQL',
        'AS_AP_General Inquiry Form_2023', 'AS_DG_Cashback2023_230714',
        'ID_PR_LG.com_I2B', 'AS_TH_Nurturing_Content download_MVi_English',
        'IT_ES_Digital Showroom Compras_Inqurytobuy_210831', 'ID_VH_Y2023',
        'AS_CB_campaña_digital_olafresca_julio_costa_2023',
        'AS_MK_BUL_Heating_Rolling_Seminar_20231002_Varna_EXP',
        'ID_HK_LG.com_I2B', 'curso_umas_septiembre_2023',
        'AS_SL_Nurturing_Content download_Rd_CST',
        'AS_MK_BUL_Heating_Rolling_Seminar_20231009_Sofia_EXP',
        'AS_IN_LG.com_I2B_2022', 'AS_IN_DealerSeminar_Jogjakarta_20230922',
        'AS_SL_Launching_100823_Multi V i_Survey_form', 'ID_CH_LG.com_I2B',
        'IT_US_Event_Xentegra Patriots Tailgate_20230917',
        'IT_UK_LG.com_I2B_Projector',
        'ID_SP_Facebook_RatailCampaing_Feb 2023',
        'IT_PL_LG.com_I2B_Monitor&Other', 'Cloud_IT_Nurture',
        'ID_MS_DigitalAO_JUN', 'ID_US_Eloqua_CorporateAlwaysOn_20230502',
        'ID_MS_Prom55UQ_JUL', 'AS_IN_NURTURING_MULTI V 5 Pro II_2023',
        'ID_US_Eloqua_CorporateAlwaysOn', 'IT_EU RHQ_UKIO 2023',
        'ID_HQ_Education_Landingpage_PR',
        'ID_AR_Linkedin_Landing Page_2022',
        'AS_TH_Nurturing_Content download_request_Hospital OP_Thai',
        'AS_SA_LG.com_I2B',
        'AS_VH_Nurturing_Content download_request_form',
        'AS_AS_LG.com_I2B_Fra_2022', 'IT_IS_lgbusiness_contactus_230707',
        'AS_SP_Seminar_(15092023)_Febrava', 'ID_US_LG.com_Join_Us',
        'IT_HQ_2023IFA IT Innovation Lounge',
        'AS_MS_Webinar_211109_GoToWebinar_Registration',
        'ID_US_Eloqua_QSRAlwaysOn_20230418', 'folleto_parque_tepeyac',
        'HVAC Design Award 2023',
        'ID_US_lg.com_vertical_markets_restaurant',
        'AS_CB_MKT_Facebook_Academia_campaign_2023', 'IDUSHelloLGESS',
        'AS_CB_campaña_digital_cac_julio_2039',
        'AS_IN_NURTURING_Refrigerant Pipe_2023',
        'AS_SP_Seminar_Integrated_(230804)_TreinamentoMaceió',
        'ID_IN_LG.com_I2B', 'AS_PR_LG.com_I2B_2022',
        'ID_US_Promotion_Facebook Digital Menu Lead Gen Ad',
        'AS_IS_Form_MULTIVi_Firenze_LaunchingEvent_091123',
        'AS_SP_EVENTO FEBRAVA ESQUADRÃO_230915', 'AS_IN_1-on-1 Training',
        'AS_MK_BOS_Heating_Rolling_Seminar_Bijeljina_20230919_EXP',
        'AS_MK_BUL_Heating_Rolling_Seminar_20231004_Plovdiv_EXP',
        'ID_LATAM_Facebook_LED Control Room_2023',
        'video_repeticion_curso_lats_hvac',
        'AS_LGEAS_Dealertrip_210523_23Dealertrip_form_MQL',
        'IT_Digital_Showroom_Catalog_Main', 'BSC Campaign',
        'IT_EU RHQ_VWE 2023', 'ID_MS_AO_AGO',
        'ID_US_Promotion_Facebook CreateBoard Lead Gen Ad',
        'as_latam_Therma_V_monobloc', 'ID_SP_Roadshow_AgisGO_May 2023',
        'ID_PL_LG.com_I2B',
        '(Survey for Customer) AS_HQ_HVAC_ASIADesignAward_2023_feedback',
        'ID_SJ_LG.com_I2B', 'AS_IN_DealerSeminar_Semarang_20231020',
        'IT_HQ_DE_Cloud_Medical_Emergency_FB_2023.09',
        'AS_IN_DealerTrip_020923_ConsultantTrip_form_MQL',
        'AS_DG_Webinar2021_Q3', 'AS_HQ_ETC_160323_PCC_form',
        'ID_US_Event_Bourbon and Blazers CLT_20230524',
        'ID_US_QSR_Nurture_20221104', 'AS_DG_ThermavChallenge2023',
        'AS_PH_Nurturing_Content download_request_maintenance',
        'IT_Global_LG.com_I2B_Cloud', 'NEWSLETTER_AUTOMATIZACIÓN',
        'AS_HS_Seminar_300623_Seminar_Multi V i_Terna_MQL attendee form',
        'ID_US_Createboard_Campaign-Site Survey', 'ID_EG_LG.com_I2B',
        'AS_SJ_LG.com_I2B_Ara_2022', 'ID_US_LG.com_CLOi-UV',
        'IT_CL_LG.com_I2B_Monitor&Other',
        'AS_HS_Seminar_170723_Multi V i_ANRG_MQL attendee form',
        'AS_Dubai_MQL_SACSeminar_Registrationform',
        'AS_PH_Inquiry Form_EDM__Incl_MQLs_form_September_2023',
        'ID_US_Awareness_AVIXA Online Education',
        'AS_SP_Treinamento LATS CAD_230228_form',
        'ID_PS_LED Hotel Entertainment Newsletter_June 2023',
        'ID_MS_ProUHOQ_JUL',
        'ID_IL_LN Conversation IDB (JULY) Lead Campaign_230713',
        'AS_SP_Evento FEBRAVA 14.09', 'LATAM_COCINA_VIETNAMITA',
        'IT_CI_LG.com_I2B_Monitor&Other_Eng',
        'IT_US_Event_LA BIC Medical Cloud Expo_20230510',
        'curso_online_repeticion', 'IT_Digital_Showroom_I2B_Global',
        'BR_SI_SURVEY', 'ID_IS_lgbusiness_contactus_230707',
        'IT_PS_LG.com_I2B_Cloud_Spa',
        'AS_PH_Inquiry Form_EDM__Incl_MQLs_form_August_2023',
        'AS_IN_Seminar_Bali_End-User_20230824', 'ID_MS_ProAIOQ_AGO',
        'IT_Global_LG.com_I2B_Laptop', 'IT_CB_LG.com_I2B_Medical',
        'AS_foro_virtual_repe_youtube', 'AS_US_ESSHelloMyNameIs',
        'AS_DG_ThermaV_Website_220208', 'ID_MS_AODigital_OCT',
        'AS_TH_Nurturing_Content download_request_Multi V i',
        'ID_LATAM_Dig Campaign_Linkedin_Hotel Room TV_Dec 2022',
        'ID_LATAM_Facebook_Hotel ProCentric_2023',
        'AS_IN_AcademyTraining_Jakarta_Oct2023',
        'ID_EU_RHQ_IBC2023_Prospect_230914', 'AS_GF_LG.com_I2B_Ara_2022',
        'ID_US_Event_Best Western Convention 2023',
        'AS_SP_Evento FEBRAVA_Esquadrão_230912',
        'ID_EB_LN_ControlroomWhitepaperForm_210511',
        'IT_US_Event_VMware Explore_20230821',
        'ID_US_Eloqua_AlwaysOn-Site Survey',
        'IT_Digital_Showroom_PJTR_Germany', 'IT_DG_LG.com_I2B_Laptop',
        'ID_IN_Business Matching V',
        'ID_CL_Education Newsletter_June 2023',
        'ID_IL_FB IDB (MAY) Lead Campaign_230501',
        'IT_HQ_ERGO_FB_UK_2022.11', 'AS_VH_Seminar_2023',
        'IT_Digital_Showroom_MNTRPC_Global',
        'AS_CL_InscCertfIf-202306202122', 'HQ_AS_RoundCassette',
        'AS_PH_Inquiry Form_EDM__Incl_MQLs_form_July 2023',
        'IT_GF_LG.com_I2B_Medical',
        'AS_MS_THANK_YOU_PAGE_CHILLER_CENTRIGUGO_2023266',
        'IT_CI_LG.com_I2B_Projector_Eng', 'IT_IL_LG.com_I2B_Monitor&Other',
        'AS_MK_HU_Heating_Rolling_Seminar_120923_Budapest',
        'AS_IN_NURTURING_MULTI V I_20230622',
        'AS_MK_SRB_Heating_Rolling_Seminar_20230925_Belgrade_EXP',
        'ID_MS_ProAIOQ_JUL', 'AS_Global_L&C_LG.com_I2B',
        'AS_MK_SRB_Heating_Rolling_Seminar_20230927_Belgrade_EXP',
        'AS_CB_campaña_digital_cac_julio_2032', 'AS_AG_LG.com_I2B_2023',
        'AS_SP_Webinar_(200723)_TeaTime',
        'AS_SL_DealerTrip_231123_VietnamTrip_form_MQL',
        'AS_CB_Webinar_230214_GoToWebinar_Registration',
        'ID_MEAHQ Campaigns_Jul2023', 'ID_HQ_SignageSolution_202305',
        'AS_EF_LG.com_I2B', 'IT_MS_LG.com_I2B_Medical',
        'AS_GF_MQL_SACSeminar_Registrationform',
        'AS_CB_PaidCampaign__Post_2023', 'ID_HQ_Education_Landingpage_ENG',
        'IT_AP_LG.com_I2B_Monitor&Other', 'AS_UK_RAC Campaign_230619',
        'AS_PH_Launching_040523_MultiViLaunch_Survey_form',
        'AS_VH_Launching_Multi V i_Survey_form',
        'AS_SP_Webinar_220317_GoToWebinar_Registration',
        'AS_IN_GLMS_20230419', 'AS_SP_Treinamento LATS REVIT',
        'HQ_InfoComm2023Badgescan_230623',
        'ID_US_lg.com_vertical_markets_transportation',
        'IT_US_LG.com_ecommerce', 'AS_CB_campaña_digital_cac_julio_2024',
        'IT_B2B Team 1_eCRM_US_1st',
        'AS_SP_230328_Webinar_LATS REVIT Abril',
        'ID_EU_RHQ_IBC2023_On site Form_V1_230731', 'ID_HK_LG.com_I2B_Eng',
        'AS_PS_LG.com_I2B_Caribbean_2022', 'IT_Global_LG.com_I2B_Medical',
        'AS_SP_ALL_ACADEMY_CONTACTS_210303_Upload_210304',
        'AS_Oman_BLT_SACSeminar20230524_Attendee_form',
        'IT_US_Event_Bourbons and Blazers Louisville_20230726',
        'ID_US_lg.com_vertical_markets_government',
        'Facebook_Campaign_UnidadTipoPared_CAC_Lead',
        'AS_SL_Nurturing_Content download_Multi V i',
        'AS_Global_Asia_LG.com_I2B_IS_Microsite',
        'ID_VH_Contact Collection_2023', 'ID_VH_LG.com_I2B',
        'AS_IN_NURTURING_SCAC R32_2023', 'AS_PS_LG.com_I2B_Panama_2022',
        'Mult_standar_SCAC_MULTI',
        "AS_HS_DealerTrip_180623_'23 LG SAC Cyprus & Greece VIP trip_form_MQL",
        'IT_US_RSNA_PF', 'IT_AP_LG.com_I2B_Cloud', 'ID_HQ_Cdisplay_Msg',
        'AS_AF_LG.com_I2B_Fra_2022', 'Curso_controles_mayo_2023',
        'IT_DG_LG.com_I2B_Projector', 'Hospitality_Nurture',
        'AS_SP_Webinar_(290623)_TeaTime',
        'ID_LATAM_Dig Campaign_Instagram_Retail Fashion Store Signage_Dec 2022',
        'ID_US_Eloqua_InfoComm_20230614',
        'AS_MK_BUL_Heating_Rolling_Seminar_20231016_Sofia_EXP',
        'ID_US_lg.com_direct-view-led-home-cinema-display',
        'AS_AP_Seminar 2208 ARBS Gathering _Attendee_form',
        'AS_CB_campaña_digital_cac_julio_2044',
        'ID_VH_Contact Collection_2022',
        'AS_AP_Nurturing_Content download_AWHP',
        'AS_MS_ROADSHOW_CHILLER_2023',
        'ID_IL_LN Conversation IDB (AUG) Lead Campaign_230801',
        'ID_SP_B2BGerp_202204', 'IT_US_Event_AHRA 2023_20230714',
        'Solution_ES_B2B_Contact_Inquiry_210224',
        'IT_US_Event_SF Giants Liquidware Event_20230517',
        'Hora_De_climatización_data_de_peru_apoyo_a_COLOMBIA',
        'ID_US_Eloqua_TransportationAlwaysOn_20230503',
        'ID_RHQ_IBC2023 Facebook Lead Gen_Prospect_230912',
        'ID_SP_JabraRoadshow_AugSep2023',
        'IT_HQ_US_Retargeting_Cloud_Medical_Emergency_FB_2023.09',
        'HQ_ID_Cdisplay_Newsletter',
        'AS_LF_Trip_ GL_230806_Jordan Consultants VIP Trip_Attendee_Form',
        'AS_SP_Webinar_220223_GoToWebinar_Registration',
        'AS_PH_Webinar_Nurturing_Content download_request_form',
        'AS_SP_Webinar_Training_210217_Chiller_Registration_GoToWebinar',
        'AS_CB_Webinar_221213_GoToWebinar_Registration',
        'AS_MK_LG.com_I2B_Bulgaria',
        'ID_LATAM_Linkedin_LED Control Room_2023',
        'IT_HQ_ERGO_FB_Germany_2022.11', 'ID_MS_ProVW_JUL',
        'IT_DG_LG.com_I2B_Medical',
        'ID_US_Madison Logic_CreateBoard Case Study',
        'AS_latam_nurturing_782022',
        'AS_CB_campaña_digital_cac_julio_2028',
        'AS_GF_AbuDhabi_Reliance Contracting Co_SACSeminar_Registrationform_20230705',
        'AS_CI_LG.com_I2B_Fra_2022',
        'AS_GF_Dubai_HAOarchitects_Registrationform_20230808',
        'IT_GF_LG.com_I2B_Monitor&Other',
        'AS_TH_Launching_230623)_Multi Vi_Survey_form_EN',
        'IT_US_Event_Xentegra Sushi Event_20230627',
        'ID_GF_LG.com_I2B_Ara', 'AS_TK_Nutruing_23Aug',
        'AS_CI_Wolseley Ontario Training_230628',
        'AS_MS_Webinar_220729_GoToWebinar_Registration',
        'IT_TH_LG.com_I2B_Monitor&Other',
        'AS_EF_Seminar_Training_230414_LGSACEVENTTZ_Attendee_Form',
        'ID_SP_CIOBrasil_Mar_2023',
        'ID_US_Eloqua_HospitalityAlwaysOn_20230502', 'ID_Digital Campaign',
        'AS_HS_Seminar_120623_Multi V i_CAC_Kanellakis_MQL attendee form',
        'AS_PS_Webinar_230720_GoToWebinar_Registration',
        'AS_AP_Dealer Trip Form_2023',
        'AS_latam_nurturing_lgthinq_2022926',
        'ID_RHQ_LG MoSys Registration_2023', 'IT_UK_LG.com_I2B_Laptop',
        'ID_AR_Webinar educacion_may 2023', 'AS_LF_LG.com_I2B_Ara_2022',
        'ID_TT_LG.com_I2B', 'AS_SP_Webinar_(010623)_FSM_STR Guarulhos',
        'AS_PH_Webinar_Nurturing_Content download_request_form_LATS',
        'AS_SP_Webinar_(280623)_Evento Presencial',

### prefer_ver_count
특정 Business Unit 기준으로 영업 전환 성공 샘플에 대해서 Vertical Level 1 비율

In [ ]:
train_prefer_ver_count = train[['prefer_ver_count']].copy()
test_prefer_ver_count = test[['prefer_ver_count']].copy()
train_prefer_ver_count['prefer_ver_count'].unique(), test_prefer_ver_count['prefer_ver_count'].unique()#0 ~ 1까지 0.25씩 있음

(array([0.07692308, 0.09543568,        nan, 0.14522822, 0.21161826,
        0.13043478, 0.28846154, 0.05809129, 0.26923077, 0.03846154,
        0.04347826, 0.01659751, 0.43478261, 0.        , 0.05769231,
        0.11538462, 0.21576763, 0.11618257, 0.07053942, 0.17391304,
        0.02489627, 0.01244813, 1.        , 0.01923077]),
 array([0.21161826, 0.05769231, 0.07692308,        nan, 0.14522822,
        0.21576763, 0.02489627, 0.09543568, 0.28846154, 0.03846154,
        0.        , 0.01659751, 0.11618257, 0.26923077, 0.07053942,
        0.13043478, 0.11538462, 0.05809129, 0.17391304, 0.01244813,
        0.43478261, 0.01923077, 0.04347826]))

### 0.434783이랑 0.043478이랑 밸류 차이는 거의 없는데 결과 차이는 정반대, 얘는 차라리 카테고리로 쓰는게 나음(cat_feature)

In [ ]:
conversion_summary = train.groupby('prefer_ver_count')['is_converted'].value_counts(normalize=True).unstack(fill_value=0).join(
    train.groupby('prefer_ver_count')['is_converted'].value_counts().unstack(fill_value=0), rsuffix='_count')
conversion_summary_with_sum = conversion_summary.assign(
    sum=lambda x: x['True_count'] + x['False_count']
).sort_values(by='sum', ascending=False)
conversion_summary_rearranged = conversion_summary_with_sum[['sum', 'True', 'False', 'True_count', 'False_count']]
conversion_summary_rearranged

is_converted       sum      True     False  True_count  False_count
prefer_ver_count
0.211618          2410  0.087552  0.912448         211         2199
0.145228          1972  0.061866  0.938134         122         1850
0.038462          1374  0.037118  0.962882          51         1323
0.269231          1355  0.017712  0.982288          24         1331
0.095436          1334  0.065967  0.934033          88         1246
0.288462          1251  0.030376  0.969624          38         1213
0.116183          1043  0.069990  0.930010          73          970
0.215768           941  0.105207  0.894793          99          842
0.000000           845  0.053254  0.946746          45          800
0.043478           829  0.003619  0.996381           3          826
0.016598           775  0.073548  0.926452          57          718
0.434783           745  0.370470  0.629530         276          469
0.115385           704  0.028409  0.971591          20          684
0.070539           533  0.067542  0.932458          36          497
0.058091           411  0.077859  0.922141          32          379
0.057692           377  0.055703  0.944297          21          356
0.173913           365  0.046575  0.953425          17          348
0.024896           209  0.066986  0.933014          14          195
0.076923           152  0.098684  0.901316          15          137
0.130435           143  0.048951  0.951049           7          136
0.019231            59  0.135593  0.864407           8           51
0.012448            43  0.279070  0.720930          12           31
1.000000            29  0.034483  0.965517           1           28

In [ ]:
train[(train['prefer_ver_count'] > 0.043477) & (train['prefer_ver_count'] < 0.043479)]

,bant_submit,expected_budget,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,lead_date,customer_type,customer_history,enterprise,...,transfer_agreement,ver_cus,ver_pro,ver_win_rate_x,ver_win_rate_mean_upper,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner,is_converted
44,0.5,NaN,Mexico,IT,NaN,43811,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
155,0.5,NaN,Mexico,IT,NaN,4385,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
190,0.5,NaN,Mexico,IT,NaN,19959,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
206,0.5,NaN,Mexico,IT,NaN,21321,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
323,0.5,NaN,Mexico,IT,NaN,33331,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56655,0.5,NaN,France,IT,NaN,40855,2021-12-16,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,819,False
56735,0.5,NaN,Mexico,IT,NaN,6267,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
56798,0.5,NaN,Mexico,IT,NaN,39432,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
56919,0.5,NaN,Mexico,IT,NaN,9282,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
56964,1.0,"Less than $50,000",/Lima/Peru,IT,NaN,38563,2021-12-25,NaN,New,SMB,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,933,False

In [ ]:
test[(test['prefer_ver_count'] > 0.043477) & (test['prefer_ver_count'] < 0.043479)]

,id,bant_submit,expected_budget,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,lead_date,customer_type,customer_history,...,transfer_agreement,ver_cus,ver_pro,ver_win_rate_x,ver_win_rate_mean_upper,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner,is_converted
1990,78753,1.00,"Less than $10,000",/ Berlin / Germany,IT,NaN,36050,2023-07-19,End Customer,New,...,NaN,1,0,0.000717,0.0,NaN,hotel & accommodation,NaN,428,NaN
2190,37415,1.00,"$100,000 ~ $200,000",/ Uk / United Kingdom,IT,NaN,25833,2023-10-15,Channel Partner,New,...,NaN,0,0,0.000717,0.0,NaN,hotel & accommodation,Casino Resort,431,NaN
2336,78754,1.00,"Less than $10,000",/ / France,IT,NaN,26606,2023-08-01,End Customer,New,...,NaN,1,0,0.000717,0.0,NaN,hotel & accommodation,NaN,474,NaN
2666,39159,1.00,"$400,000 ~ $600,000",/ Wiesbaden / Germany,IT,NaN,26886,2023-10-21,Specifier/ Influencer,New,...,NaN,0,0,0.000026,1.0,NaN,public facility,NaN,863,NaN
4139,78752,1.00,"$50,000 ~ $100,000",/ Melbourne / Australia,IT,NaN,2368,2023-07-20,Channel Partner,New,...,NaN,0,0,0.000717,0.0,NaN,hotel & accommodation,Hotel,390,NaN
4814,80266,0.75,"Less than $10,000",/ Düsseldorf / Germany,IT,NaN,27280,2023-08-03,End Customer,Existing,...,NaN,0,0,0.000026,1.0,NaN,public facility,NaN,428,NaN
4925,80268,1.00,"$200,000 ~ $400,000",/ Budapest / Hungary,IT,NaN,14764,2023-07-15,End Customer,New,...,NaN,0,0,0.000026,1.0,NaN,public facility,Others,158,NaN
5049,80264,1.00,"Less than $10,000",/ / Germany,IT,NaN,4877,2023-08-01,End Customer,New,...,NaN,0,0,0.000026,1.0,NaN,public facility,NaN,428,NaN
11304,39158,0.25,NaN,233 South Beaudry Avenue Los Angeles CA,IT,NaN,25855,2023-09-27,End Customer,New,...,NaN,0,0,0.000026,1.0,NaN,public facility,Others,375,NaN
14477,39157,0.75,"More than $1,000,000",/ Sharjah / U.A.E,IT,NaN,2150,2023-07-29,Service Partner,New,...,NaN,0,0,0.000026,1.0,NaN,public facility,NaN,425,NaN
20766,37416,1.00,"$100,000 ~ $200,000",/ Uk / Germany,IT,NaN,23337,2023-10-15,Channel Partner,New,...,NaN,0,0,0.000717,0.0,NaN,hotel & accommodation,Cruise,863,NaN
21146,39156,1.00,"Less than $10,000",/Oxfordshire/United Kingdom,IT,NaN,28583,2023-06-21,End Customer,New,...,Y,0,0,0.000026,1.0,NaN,public facility,Museum / Gallery,426,NaN

### prefer_ver_mean
‘prefer_ver_count’ 와 동일한 기준으로 계산되며 샘플 개수가 아닌 이익 값의 비율

In [ ]:
# "prefer_ver_mean" 피처의 train 데이터셋과 test 데이터셋(여기서는 submission 데이터셋으로 가정)의 고유값 비교
train_prefer_ver_mean_unique = set(train['prefer_ver_mean'].unique())
submission_prefer_ver_mean_unique = set(test['prefer_ver_mean'].unique())

# 두 데이터셋에서 "prefer_ver_mean" 피처의 고유값이 모두 같은지 확인
are_values_identical = train_prefer_ver_mean_unique == submission_prefer_ver_mean_unique

are_values_identical, len(train_prefer_ver_mean_unique), len(submission_prefer_ver_mean_unique)

(False, 30, 29)

In [ ]:
train_prefer_ver_mean = train[['prefer_ver_mean']].copy()
test_prefer_ver_mean = test[['prefer_ver_mean']].copy()
train_prefer_ver_mean['prefer_ver_mean'].unique(), test_prefer_ver_mean['prefer_ver_mean'].unique()#0 ~ 1까지 0.25씩 있음

(array([0.01964817, 0.06771804,        nan, 0.10351139, 0.02775566,
        0.11086892, 0.01662405, 0.06828766, 0.00349357, 0.06792683,
        0.20827492, 0.13097958, 0.4456556 , 0.        , 0.00567704,
        0.00894398, 0.39132051, 0.04622018, 0.03888582, 0.04416258,
        0.04993932, 0.03271702, 0.4498716 , 0.07219541, 0.02576436,
        0.05213623, 0.10611456, 0.29066086, 1.        , 0.00377723]),
 array([0.02775566, 0.00567704, 0.01964817,        nan, 0.10351139,
        0.04622018, 0.10611456, 0.06771804, 0.01662405, 0.00894398,
        0.        , 0.03271702, 0.02576436, 0.03888582, 0.00349357,
        0.04993932, 0.04416258, 0.13097958, 0.11086892, 0.39132051,
        0.4498716 , 0.06828766, 0.07219541, 0.29066086, 0.4456556 ,
        0.00377723, 0.06792683, 0.20827492, 0.05213623]))

In [ ]:
conversion_summary = train.groupby('prefer_ver_mean')['is_converted'].value_counts(normalize=True).unstack(fill_value=0).join(
    train.groupby('prefer_ver_mean')['is_converted'].value_counts().unstack(fill_value=0), rsuffix='_count')
conversion_summary_with_sum = conversion_summary.assign(
    sum=lambda x: x['True_count'] + x['False_count']
).sort_values(by='sum', ascending=False)
conversion_summary_rearranged = conversion_summary_with_sum[['sum', 'True', 'False', 'True_count', 'False_count']]
conversion_summary_rearranged

is_converted      sum      True     False  True_count  False_count
prefer_ver_mean
0.027756         2410  0.087552  0.912448         211         2199
0.103511         1972  0.061866  0.938134         122         1850
0.003494         1355  0.017712  0.982288          24         1331
0.067718         1334  0.065967  0.934033          88         1246
0.016624         1251  0.030376  0.969624          38         1213
0.038886         1043  0.069990  0.930010          73          970
0.046220          941  0.105207  0.894793          99          842
0.000000          845  0.053254  0.946746          45          800
0.208275          789  0.002535  0.997465           2          787
0.008944          781  0.026889  0.973111          21          760
0.445656          745  0.370470  0.629530         276          469
0.391321          704  0.028409  0.971591          20          684
0.049939          533  0.067542  0.932458          36          497
0.068288          411  0.077859  0.922141          32          379
0.449872          398  0.060302  0.939698          24          374
0.044163          379  0.039578  0.960422          15          364
0.072195          325  0.033846  0.966154          11          314
0.025764          265  0.094340  0.905660          25          240
0.106115          209  0.066986  0.933014          14          195
0.005677          207  0.067633  0.932367          14          193
0.067927          195  0.030769  0.969231           6          189
0.110869          183  0.043716  0.956284           8          175
0.032717          170  0.041176  0.958824           7          163
0.019648          152  0.098684  0.901316          15          137
0.130980          131  0.129771  0.870229          17          114
0.003777           59  0.135593  0.864407           8           51
0.290661           43  0.279070  0.720930          12           31
0.052136           40  0.150000  0.850000           6           34
1.000000           29  0.034483  0.965517           1           28

In [ ]:
train[(train['prefer_ver_mean'] > 0.208274) & (train['prefer_ver_mean'] < 0.208276)]

,bant_submit,expected_budget,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,lead_date,customer_type,customer_history,enterprise,...,transfer_agreement,ver_cus,ver_pro,ver_win_rate_x,ver_win_rate_mean_upper,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner,is_converted
44,0.5,NaN,Mexico,IT,NaN,43811,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
155,0.5,NaN,Mexico,IT,NaN,4385,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
190,0.5,NaN,Mexico,IT,NaN,19959,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
206,0.5,NaN,Mexico,IT,NaN,21321,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
323,0.5,NaN,Mexico,IT,NaN,33331,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56655,0.5,NaN,France,IT,NaN,40855,2021-12-16,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,819,False
56735,0.5,NaN,Mexico,IT,NaN,6267,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
56798,0.5,NaN,Mexico,IT,NaN,39432,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
56919,0.5,NaN,Mexico,IT,NaN,9282,2021-12-27,NaN,New,Enterprise,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,816,False
56964,1.0,"Less than $50,000",/Lima/Peru,IT,NaN,38563,2021-12-25,NaN,New,SMB,...,Y,0,0,0.000717,0.0,NaN,hotel & accommodation,NaN,933,False

In [ ]:
test[(test['prefer_ver_mean'] > 0.208274) & (test['prefer_ver_mean'] < 0.208276)]

,id,bant_submit,expected_budget,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,lead_date,customer_type,customer_history,...,transfer_agreement,ver_cus,ver_pro,ver_win_rate_x,ver_win_rate_mean_upper,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner,is_converted
1990,78753,1.0,"Less than $10,000",/ Berlin / Germany,IT,NaN,36050,2023-07-19,End Customer,New,...,NaN,1,0,0.000717,0.0,NaN,hotel & accommodation,NaN,428,NaN
2190,37415,1.0,"$100,000 ~ $200,000",/ Uk / United Kingdom,IT,NaN,25833,2023-10-15,Channel Partner,New,...,NaN,0,0,0.000717,0.0,NaN,hotel & accommodation,Casino Resort,431,NaN
2336,78754,1.0,"Less than $10,000",/ / France,IT,NaN,26606,2023-08-01,End Customer,New,...,NaN,1,0,0.000717,0.0,NaN,hotel & accommodation,NaN,474,NaN
4139,78752,1.0,"$50,000 ~ $100,000",/ Melbourne / Australia,IT,NaN,2368,2023-07-20,Channel Partner,New,...,NaN,0,0,0.000717,0.0,NaN,hotel & accommodation,Hotel,390,NaN
20766,37416,1.0,"$100,000 ~ $200,000",/ Uk / Germany,IT,NaN,23337,2023-10-15,Channel Partner,New,...,NaN,0,0,0.000717,0.0,NaN,hotel & accommodation,Cruise,863,NaN

### transfer_agreement
Lead 정보 국외 반출 동의 여부

In [ ]:
train_transfer_agreement = train[['transfer_agreement']].copy()
test_transfer_agreement = test[['transfer_agreement']].copy()
train_transfer_agreement['transfer_agreement'].unique(), test_transfer_agreement['transfer_agreement'].unique()#0 ~ 1까지 0.25씩 있음

(array(['Y', 'N', nan], dtype=object), array([nan, 'Y', 'N'], dtype=object))

In [ ]:
train_transfer_agreement['transfer_agreement'].value_counts(), test_transfer_agreement['transfer_agreement'].value_counts()

(transfer_agreement
 Y    47462
 N     9073
 Name: count, dtype: int64,
 transfer_agreement
 Y    2599
 N     225
 Name: count, dtype: int64)

In [ ]:
conversion_summary = train.groupby('transfer_agreement')['is_converted'].value_counts(normalize=True).unstack(fill_value=0).join(
    train.groupby('transfer_agreement')['is_converted'].value_counts().unstack(fill_value=0), rsuffix='_count')
conversion_summary_with_sum = conversion_summary.assign(
    sum=lambda x: x['True_count'] + x['False_count']
).sort_values(by='sum', ascending=False)
conversion_summary_rearranged = conversion_summary_with_sum[['sum', 'True', 'False', 'True_count', 'False_count']]
conversion_summary_rearranged

is_converted          sum      True     False  True_count  False_count
transfer_agreement
Y                   47462  0.091715  0.908285        4353        43109
N                    9073  0.031853  0.968147         289         8784

### ver_win_rate_mean_upper
Ratio_oppty – Ratio 값을 구해서 Vertical 별 평균 값보다 클 경우 1, 아니면 0 값으로 표현

In [ ]:
train_ver_win_rate_mean_upper = train[['ver_win_rate_mean_upper']].copy()
test_ver_win_rate_mean_upper = test[['ver_win_rate_mean_upper']].copy()
train_ver_win_rate_mean_upper['ver_win_rate_mean_upper'].unique(), test_ver_win_rate_mean_upper['ver_win_rate_mean_upper'].unique()#0 ~ 1까지 0.25씩 있음

(array([ 1.,  0., nan]), array([ 0.,  1., nan]))

In [ ]:
train_ver_win_rate_mean_upper['ver_win_rate_mean_upper'].value_counts(), test_ver_win_rate_mean_upper['ver_win_rate_mean_upper'].value_counts()

(ver_win_rate_mean_upper
 0.0    14307
 1.0     3592
 Name: count, dtype: int64,
 ver_win_rate_mean_upper
 0.0    6126
 1.0    2121
 Name: count, dtype: int64)

In [ ]:
conversion_summary = train.groupby('ver_win_rate_mean_upper')['is_converted'].value_counts(normalize=True).unstack(fill_value=0).join(
    train.groupby('ver_win_rate_mean_upper')['is_converted'].value_counts().unstack(fill_value=0), rsuffix='_count')
conversion_summary_with_sum = conversion_summary.assign(
    sum=lambda x: x['True_count'] + x['False_count']
).sort_values(by='sum', ascending=False)
conversion_summary_rearranged = conversion_summary_with_sum[['sum', 'True', 'False', 'True_count', 'False_count']]
conversion_summary_rearranged

is_converted               sum      True     False  True_count  False_count
ver_win_rate_mean_upper
0.0                      14307  0.053820  0.946180         770        13537
1.0                       3592  0.139198  0.860802         500         3092

### customer_history

In [ ]:
train_customer_history = train[['customer_history']].copy()
test_customer_history = test[['customer_history']].copy()
train_customer_history['customer_history'].unique(), test_customer_history['customer_history'].unique()#0 ~ 1까지 0.25씩 있음

(array(['Existing', 'New'], dtype=object),
 array(['New', 'Existing'], dtype=object))

In [ ]:
train.drop(['expected_budget','lead_date','lead_from_channel','lead_description','event_name','prefer_ver_count','prefer_ver_mean','transfer_agreement','ver_win_rate_mean_upper'],axis=1,inplace=True)

In [ ]:
train.to_csv('train_aim_check.csv',index=False)

In [ ]:
train

,bant_submit,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,customer_type,customer_history,enterprise,historical_existing_cnt,id_strategic_ver,...,response_corporate,expected_timeline,ver_cus,ver_pro,ver_win_rate_x,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner,is_converted
0,0.75,/DKI Jakarta/Indonesia,AS,NaN,33931,End-Customer,Existing,Enterprise,4.0,NaN,...,LGEIN,less than 3 months,0,0,0.000060,0.128571,hospital & health care,General Hospital,870,False
1,0.25,/Minneola/United States,ID,0.390244,42490,NaN,New,SMB,NaN,NaN,...,LGEUS,NaN,0,0,0.000572,0.048630,education,NaN,501,True
2,0.25,4880 Stevens Creek Blvd Cloud IT/Hollywood/Un...,IT,NaN,10350,Solution Eco-Partner,New,SMB,NaN,NaN,...,LGEUS,NaN,0,0,NaN,NaN,NaN,NaN,375,True
3,1.00,/Wiesbaden/Germany,ID,0.017544,19750,NaN,New,SMB,NaN,NaN,...,LGEDG,less than 3 months,0,0,0.000572,0.048630,education,NaN,359,False
4,0.50,//Singapore,ID,NaN,45802,Specifier/ Influencer,New,SMB,NaN,NaN,...,LGESL,less than 3 months,0,0,NaN,NaN,NaN,NaN,198,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59294,0.75,/Noida/India,ID,NaN,17289,NaN,Existing,Enterprise,3.0,NaN,...,LGEIL,3 months ~ 6 months,0,0,NaN,NaN,NaN,NaN,174,False
59295,0.75,/Sao Bernardo do Campo/Brazil,ID,NaN,23686,NaN,New,SMB,NaN,NaN,...,LGESP,3 months ~ 6 months,0,0,NaN,NaN,NaN,NaN,211,False
59296,0.50,/Alexandria/Egypt,AS,0.049689,29370,NaN,Existing,Enterprise,1.0,NaN,...,LGEEG,NaN,0,0,0.000298,0.020121,residential (home),NaN,56,False
59297,0.50,/Mogi guaçu SP /Brazil,AS,NaN,22609,NaN,New,Enterprise,NaN,NaN,...,LGESP,NaN,0,0,NaN,NaN,NaN,NaN,96,False
59298,0.50,//United Kingdom,IT,NaN,41443,NaN,New,SMB,NaN,NaN,...,LGEUK,NaN,0,0,NaN,NaN,NaN,NaN,384,False

## old prepro

In [ ]:
train = pd.read_csv("/content/drive/MyDrive/LG_Aimers4_본선/train_old_prepro.csv")
test = pd.read_csv("/content/drive/MyDrive/LG_Aimers4_본선/test_old_prepro.csv")
train

,bant_submit,expected_budget,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,lead_date,customer_type,customer_history,enterprise,...,ratio_rate,log_ratio_rate,gob1,gob2,gob3,gob4,gob5,gob6,cluster_1,cluster_2
0,0.75,67,74,0,NaN,26590,566,8,0,0,...,2127.245407,7.663053,NaN,63817.362216,8508.981629,120.0,NaN,NaN,2,2
1,0.25,67,166,2,0.390244,36098,793,25,1,1,...,85.023333,4.454619,33.179837,3911.073326,NaN,NaN,17.951220,NaN,2,2
2,0.25,67,166,3,NaN,393,751,20,1,1,...,0.000000,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,2,0
3,1.00,4,60,2,0.017544,10833,223,25,1,1,...,85.023333,4.454619,1.491637,19725.413298,NaN,NaN,4.070175,NaN,1,1
4,0.50,67,141,2,NaN,39777,743,21,1,1,...,0.000000,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55284,0.75,67,73,2,NaN,8098,105,25,0,0,...,0.000000,0.000000,NaN,0.000000,0.000000,393.0,NaN,NaN,1,1
55285,0.75,67,26,2,NaN,15206,129,25,1,1,...,0.000000,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,2,2
55286,0.50,67,50,0,0.049689,21522,158,25,0,0,...,67.448952,4.226088,3.351501,2900.304957,67.448952,43.0,2.136646,0.049689,2,2
55287,0.50,67,26,0,NaN,14010,398,25,1,0,...,0.000000,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,2,2
55288,0.50,79,165,3,NaN,34935,534,25,1,1,...,0.000000,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,2,0

In [ ]:
# Simplified text preprocessing function
def simplify_preprocess_text(text):
    # Convert text to lowercase and remove non-letter characters
    text = re.sub(r'[^a-zA-Z]', ' ', text.lower())
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Apply the simplified preprocessing to the 'lead_description'
train['lead_description_clean_simple'] = train['lead_description'].astype(str).apply(simplify_preprocess_text)

# Vectorizing the preprocessed text with TF-IDF, simplified version
tfidf_vectorizer_simple = TfidfVectorizer(max_features=1000)  # Keeping the features to 1000 for demonstration
tfidf_matrix_simple = tfidf_vectorizer_simple.fit_transform(train['lead_description_clean_simple'])

tfidf_matrix_simple.shape

(59299, 1000)

In [ ]:
tfidf_matrix_simple

<59299x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 311586 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import nltk

# Downloading NLTK resources (stopwords, punkt for tokenization, wordnet for lemmatization)
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

# Define a function for text preprocessing
def preprocess_text(text):
    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    # Remove non-letters and lower case all words
    text = re.sub(r'[^a-zA-Z]', ' ', text).lower()
    # Tokenize
    words = word_tokenize(text)
    # Remove stopwords
    words = [w for w in words if w not in stopwords.words('english')]
    # Lemmatize
    lemmatizer = WordNetLemmatizer()
    words = [lemmatizer.lemmatize(w) for w in words]
    # Join the words back into one string
    return ' '.join(words)

# Applying the preprocessing function to the 'lead_description' column
train['lead_description_clean'] = train['lead_description'].astype(str).apply(preprocess_text)

# Vectorizing the preprocessed text
tfidf_vectorizer = TfidfVectorizer(max_features=1000)  # Limiting to 1000 features for demonstration
tfidf_matrix = tfidf_vectorizer.fit_transform(train['lead_description_clean'])

tfidf_matrix.shape

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

(59299, 1000)

In [ ]:
train['lead_description_clean'].to_csv("aaaa.csv",index=False)

In [ ]:
# TF-IDF 벡터를 데이터 프레임으로 변환
tfidf_df = pd.DataFrame(tfidf_matrix_simple.toarray(), columns=tfidf_vectorizer_simple.get_feature_names_out())

# 기존 데이터 프레임과 결합하기 전에, 인덱스를 맞춰주어야 합니다. 이 경우 train의 인덱스를 사용합니다.
tfidf_df.index = train.index

# 기존의 데이터 프레임과 TF-IDF 데이터 프레임을 결합합니다. 여기서는 단순화를 위해 몇 개의 수치형 피처만 선택하여 결합해 보겠습니다.
# 실제로는 모델링에 필요한 모든 수치형 피처를 포함시켜야 합니다.
selected_numerical_features = train.select_dtypes(include=['int64', 'float64']).drop(columns=['customer_idx'])
combined_df = pd.concat([selected_numerical_features, tfidf_df], axis=1)

combined_df

,bant_submit,com_reg_ver_win_rate,historical_existing_cnt,id_strategic_ver,it_strategic_ver,idit_strategic_ver,lead_desc_length,prefer_ver_count,prefer_ver_mean,ver_cus,...,xe,xxx,xxxxx,xxxxxot,xxxxxpping,year,years,yes,you,your
0,0.75,NaN,4.0,NaN,NaN,NaN,30,0.076923,0.019648,0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1,0.25,0.390244,NaN,NaN,NaN,NaN,46,0.095436,0.067718,0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
2,0.25,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
3,1.00,0.017544,NaN,NaN,NaN,NaN,232,0.095436,0.067718,0,...,0.0,0.0,0.118307,0.0,0.0,0.0,0.0,0.0,0.125126,0.0
4,0.50,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59294,0.75,NaN,3.0,NaN,NaN,NaN,131,NaN,NaN,0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
59295,0.75,NaN,NaN,NaN,NaN,NaN,31,NaN,NaN,0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
59296,0.50,0.049689,1.0,NaN,NaN,NaN,43,0.269231,0.003494,0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
59297,0.50,NaN,NaN,NaN,NaN,NaN,22,NaN,NaN,0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
59298,0.50,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

In [ ]:

train['event_name_first_part'] = train['event_name'].apply(lambda x: x.split('_', 1)[0] if pd.notnull(x) else x)
def extract_second_part(event_name):
    if pd.isnull(event_name):
        return event_name
    parts = event_name.split('_', 1)
    if len(parts) > 1:
        second_part = re.split('_| ', parts[1], 1)[0]
        return second_part
    return None

train['event_name_second_part'] = train['event_name'].apply(extract_second_part)

,event_name,event_name_first_part,event_name_second_part
0,AS_IN_LG.com_I2B_2022,AS,IN_LG.com_I2B_2022
1,ID_US_Createboard_Campaign,ID,US_Createboard_Campaign
2,IT_US_Cloud_IT_VMUG_UserCon_Event_Leads_230323,IT,US_Cloud_IT_VMUG_UserCon_Event_Leads_230323
3,ID_HQ_LG.com_I2B,ID,HQ_LG.com_I2B
4,ID_SL_LG.com_I2B_Dev,ID,SL_LG.com_I2B_Dev

In [ ]:
def extract_second_part(event_name):
    if pd.isnull(event_name):
        return event_name
    parts = event_name.split('_', 1)
    if len(parts) > 1:
        second_part = re.split('_| ', parts[1], 1)[0]
        return second_part
    return None

train['event_name_second_part'] = train['event_name'].apply(extract_second_part)

train[['event_name', 'event_name_first_part', 'event_name_second_part']].to_csv("Checking_event.csv",index=False)